cc_binary(
    name = "app1",
    srcs = [
        "include/app1_main.hpp",
        "src/app1_main.cpp",
    ],
    copts = [
        "-Wall",
        "-O3",
    ],
    includes = ["include"],
    deps = ["//libs/lib1"],
)
