cc_library(
    name = "lib1",
    srcs = [
        "include/lib1_impl.hpp",
        "src/lib1.cpp",
    ],
    hdrs = ["include/lib1/lib1.hpp"],
    copts = [
        "-Wall",
        "-O3",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)
